---
title: "Classification Models"
author: "Ellison Taylor"
date: "10/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


##Does not go in full file (would be duplicated)
```{r}
charity <- read.csv("~/Desktop/School work/BC Data Analytics/ADEC7430-KBFinal/charity.csv")
##View(charity)
RNGversion("3.5.3")
library(boot)
library(ISLR)
library(lars)
library(leaps)
library(glmnet)
library(pls)
library(MASS)
```

##Does not go in full file (would be duplicated)

```{r}
# predictor transformations

charity.t <- charity
charity.t$avhv <- log(charity.t$avhv)
# add further transformations if desired
# for example, some statistical methods can struggle when predictors are highly skewed

# set up data for analysis

data.train <- charity.t[charity$part=="train",]
x.train <- data.train[,2:21]
c.train <- data.train[,22] # donr
n.train.c <- length(c.train) # 3984
y.train <- data.train[c.train==1,23] # damt for observations with donr=1
n.train.y <- length(y.train) # 1995

data.valid <- charity.t[charity$part=="valid",]
x.valid <- data.valid[,2:21]
c.valid <- data.valid[,22] # donr
n.valid.c <- length(c.valid) # 2018
y.valid <- data.valid[c.valid==1,23] # damt for observations with donr=1
n.valid.y <- length(y.valid) # 999

data.test <- charity.t[charity$part=="test",]
n.test <- dim(data.test)[1] # 2007
x.test <- data.test[,2:21]

x.train.mean <- apply(x.train, 2, mean)
x.train.sd <- apply(x.train, 2, sd)
x.train.std <- t((t(x.train)-x.train.mean)/x.train.sd) # standardize to have zero mean and unit sd
apply(x.train.std, 2, mean) # check zero mean
apply(x.train.std, 2, sd) # check unit sd
data.train.std.c <- data.frame(x.train.std, donr=c.train) # to classify donr
data.train.std.y <- data.frame(x.train.std[c.train==1,], damt=y.train) # to predict damt when donr=1

x.valid.std <- t((t(x.valid)-x.train.mean)/x.train.sd) # standardize using training mean and sd
data.valid.std.c <- data.frame(x.valid.std, donr=c.valid) # to classify donr
data.valid.std.y <- data.frame(x.valid.std[c.valid==1,], damt=y.valid) # to predict damt when donr=1

x.test.std <- t((t(x.test)-x.train.mean)/x.train.sd) # standardize using training mean and sd
data.test.std <- data.frame(x.test.std)

```


## From provided Code
```{r}
##### CLASSIFICATION MODELING ######

# linear discriminant analysis
model.cl1 <- lda(donr ~ reg1 + reg2 + reg3 + reg4 + home + chld + hinc + I(hinc^2) + genf + wrat + 
                    avhv + incm + inca + plow + npro + tgif + lgif + rgif + tdon + tlag + agif, 
                  data.train.std.c) 


post.valid.cl1 <- predict(model.cl1, data.valid.std.c)$posterior[,2] 

profit.cl1 <- cumsum(14.5*c.valid[order(post.valid.cl1, decreasing=T)]-2)
plot(profit.cl1) 
n.mail.valid.cl1 <- which.max(profit.cl1) 
c(n.mail.valid.cl1, max(profit.cl1)) 


cutoff.cl1 <- sort(post.valid.cl1, decreasing=T)[n.mail.valid.cl1+1] 
chat.valid.cl1 <- ifelse(post.valid.cl1>cutoff.cl1, 1, 0) 
table(chat.valid.cl1, c.valid) 

```


```{r}
# logistic regression - from provided code
model.log1 <- glm(donr ~ reg1 + reg2 + reg3 + reg4 + home + chld + hinc + I(hinc^2) + genf + wrat + 
                    avhv + incm + inca + plow + npro + tgif + lgif + rgif + tdon + tlag + agif, 
                  data.train.std.c, family=binomial("logit"))

post.valid.log1 <- predict(model.log1, data.valid.std.c, type="response") 



profit.log1 <- cumsum(14.5*c.valid[order(post.valid.log1, decreasing=T)]-2)
plot(profit.log1) 
n.mail.valid <- which.max(profit.log1)
c(n.mail.valid, max(profit.log1)) 


cutoff.log1 <- sort(post.valid.log1, decreasing=T)[n.mail.valid+1] 
chat.valid.log1 <- ifelse(post.valid.log1>cutoff.log1, 1, 0) 
table(chat.valid.log1, c.valid) 


post.test <- predict(model.log1, data.test.std, type="response") 

n.mail.valid <- which.max(profit.log1)
tr.rate <- .1 
vr.rate <- .5 
adj.test.1 <- (n.mail.valid/n.valid.c)/(vr.rate/tr.rate) 
adj.test.0 <- ((n.valid.c-n.mail.valid)/n.valid.c)/((1-vr.rate)/(1-tr.rate)) 
adj.test <- adj.test.1/(adj.test.1+adj.test.0) 
n.mail.test <- round(n.test*adj.test, 0) 

cutoff.test <- sort(post.test, decreasing=T)[n.mail.test+1] 
chat.test <- ifelse(post.test>cutoff.test, 1, 0) 
table(chat.test)
```

## Our Classifcation Models

```{r}
# our first linear discriminant analysis
model.cl3 <- lda(donr ~  home + chld + hinc + genf + wrat + avhv + incm + inca + plow + npro + tgif + lgif + rgif + tdon + tlag + agif, data.train.std.c) 
post.valid.cl3 <- predict(model.cl3, data.valid.std.c)$posterior[,2] 


profit.cl3 <- cumsum(14.5*c.valid[order(post.valid.cl3, decreasing=T)]-2)
plot(profit.cl3) 
n.mail.valid.cl3 <- which.max(profit.cl3)
c(n.mail.valid.cl3, max(profit.cl3)) 

cutoff.cl3 <- sort(post.valid.cl3, decreasing=T)[n.mail.valid.cl3+1] 
chat.valid.cl3 <- ifelse(post.valid.cl3>cutoff.cl3, 1, 0) 
table(chat.valid.cl3, c.valid) 


## second LDA

model.cl4 <- lda(donr ~  avhv + inca + npro + tgif+ tdon + agif, data.train.std.c) 
post.valid.cl4 <- predict(model.cl4, data.valid.std.c)$posterior[,2] 


profit.cl4 <- cumsum(14.5*c.valid[order(post.valid.cl4, decreasing=T)]-2)
plot(profit.cl4) 
n.mail.valid.cl4 <- which.max(profit.cl4)
c(n.mail.valid.cl4, max(profit.cl4)) 

cutoff.cl4 <- sort(post.valid.cl4, decreasing=T)[n.mail.valid.cl4+1] 
chat.valid.cl4 <- ifelse(post.valid.cl4>cutoff.cl4, 1, 0) 
table(chat.valid.cl4, c.valid) 



## Third LDA

model.cl5 <- lda(donr ~  reg1+ reg2 + reg3 + reg4+ plow+ avhv + inca + npro + tgif+ tdon + agif, data.train.std.c) 
post.valid.cl5 <- predict(model.cl5, data.valid.std.c)$posterior[,2] 


profit.cl5 <- cumsum(14.5*c.valid[order(post.valid.cl5, decreasing=T)]-2)
plot(profit.cl5) 
n.mail.valid.cl5 <- which.max(profit.cl5)
c(n.mail.valid.cl5, max(profit.cl5)) 

cutoff.cl5 <- sort(post.valid.cl5, decreasing=T)[n.mail.valid.cl5+1] 
chat.valid.cl5 <- ifelse(post.valid.cl5>cutoff.cl5, 1, 0) 
table(chat.valid.cl5, c.valid) 
```

## Our logistic regression models

```{r}
model.cl6 <- glm(donr ~ home + chld + hinc + genf + wrat + avhv + incm + inca + plow + npro + tgif + lgif + rgif + tdon + tlag + agif, data.train.std.c, family=binomial("logit"))

post.valid.cl6 <- predict(model.cl6 , data.valid.std.c, type="response") 

profit.cl6 <- cumsum(14.5*c.valid[order(post.valid.cl6 , decreasing=T)]-2)
plot(profit.cl6 ) 
n.mail.valid <- which.max(profit.cl6 )
c(n.mail.valid, max(profit.cl6 )) 

cutoff.cl6  <- sort(post.valid.cl6 , decreasing=T)[n.mail.valid+1] 
chat.valid.cl6  <- ifelse(post.valid.cl6 >cutoff.cl6 , 1, 0) 
table(chat.valid.cl6 , c.valid) 

## No qualitative predictors

model.cl7 <- glm(donr ~  chld +  avhv + inca + plow + npro + tgif + lgif + rgif + tdon + tlag + agif, data.train.std.c, family=binomial("logit"))

post.valid.cl7 <- predict(model.cl7 , data.valid.std.c, type="response") 

profit.cl7 <- cumsum(14.5*c.valid[order(post.valid.cl7 , decreasing=T)]-2)
plot(profit.cl7) 
n.mail.valid <- which.max(profit.cl7)
c(n.mail.valid, max(profit.cl7)) 

cutoff.cl7 <- sort(post.valid.cl7 , decreasing=T)[n.mail.valid+1] 
chat.valid.cl7<- ifelse(post.valid.cl7>cutoff.cl7 , 1, 0) 
table(chat.valid.cl7 , c.valid) 
```

